### ISSUE TITLE
Empty styling

### ISSUE THREAD

**Issue by oldmartijntje** [Pr0xximity999/Blog#7]
![image](https://github.com/Pr0xximity999/Blog/assets/64547812/ea3ea475-747f-4b90-b6b8-a22efed00bb0)
![image](https://github.com/Pr0xximity999/Blog/assets/64547812/00cbdbf6-e8c5-4e4e-9a8e-1753bf0f696a)

When the button is clicked, the button goes away. But it leaves an empty space.

**Comment by Pr0xximity999** [comment]
:(

**Comment by Pr0xximity999** [comment]
The element on the right of it is bigger so it wont get smaller
![image](https://github.com/Pr0xximity999/Blog/assets/89969567/d24ef759-b18d-4d40-87c5-275bfa5f5065)
![image](https://github.com/Pr0xximity999/Blog/assets/89969567/48c6a91e-541b-4b45-a44b-63c953d97334)
